language: go
go: 1.2
install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint
  # - go vet ./...
  # - golint **/*.go
  - golint sms/**/*.go
  - go vet sms
  - go get -d -v -t ./...
