language: go
go: 1.2
before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint
install:
  - go get -d -v -t ./...
script:
  # - go vet ./...
  # - golint **/*.go
  - $HOME/gopath/bin/golint sms/**/*.go
