language: go
go: 1.2
before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint
install:
  - go get -d -v -t ./...
script:
  - go vet ./...
  # - golint **/*.go
  - $HOME/gopath/bin/golint accounts/**/*.go
  - $HOME/gopath/bin/golint applications/**/*.go
  - $HOME/gopath/bin/golint common/**/*.go
  - $HOME/gopath/bin/golint conference/**/*.go
  - $HOME/gopath/bin/golint notifications/**/*.go
  - $HOME/gopath/bin/golint numbers/**/*.go
  - $HOME/gopath/bin/golint sms/**/*.go
  - $HOME/gopath/bin/golint */.go
after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
